In [187]:
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler


df = pd.read_csv('/home/ubuntu/Documents/TripAdvisor.csv',sep=',',header=0)

cols = ['User country',  'Period of stay', 'Traveler type', 'Pool', 'Gym',
       'Tennis court', 'Spa', 'Casino', 'Free internet', 'Hotel name',
       'User continent',
       'Review month', 'Review weekday']

In [188]:
from sklearn.base import BaseEstimator, TransformerMixin

class ToNumbers(BaseEstimator, TransformerMixin):
    def __init__(self, cols):
        self.cols = cols
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        print(type(X))
        for c in cols:
            encoded, categories = X[c].factorize()
            X[c] = encoded
        return X

In [189]:
pipeline = Pipeline([ 
    ('toNumbers', ToNumbers(cols))
])

data = pipeline.fit_transform(df)

<class 'pandas.core.frame.DataFrame'>

In [190]:
data

,User country,Nr. reviews,Nr. hotel reviews,Helpful votes,Score,Period of stay,Traveler type,Pool,Gym,Tennis court,Spa,Casino,Free internet,Hotel name,Hotel stars,Nr. rooms,User continent,Member years,Review month,Review weekday
0,0,11,4,13,5,0,0,0,0,0,0,0,0,0,3,3773,0,9,0,0
1,0,119,21,75,3,0,1,0,0,0,0,0,0,0,3,3773,0,3,0,1
2,0,36,9,25,5,1,2,0,0,0,0,0,0,0,3,3773,0,2,1,2
3,1,14,7,14,4,1,0,0,0,0,0,0,0,0,3,3773,1,6,1,1
4,2,5,5,2,4,1,3,0,0,0,0,0,0,0,3,3773,0,7,2,3
5,2,31,8,27,3,1,4,0,0,0,0,0,0,0,3,3773,0,2,2,3
6,1,45,12,46,4,1,4,0,0,0,0,0,0,0,3,3773,1,4,3,1
7,0,2,1,4,4,1,2,0,0,0,0,0,0,0,3,3773,0,0,3,3
8,3,24,3,8,4,1,0,0,0,0,0,0,0,0,3,3773,2,3,4,2
9,2,12,7,11,3,1,2,0,0,0,0,0,0,0,3,3773,0,5,4,3
10,0,102,24,58,2,2,2,0,0,0,0,0,0,0,3,3773,0,9,5,1
11,4,20,9,24,3,2,0,0,0,0,0,0,0,0,3,3773,3,4,5,2
12,0,7,6,9,2,2,0,0,0,0,0,0,0,0,3,3773,0,1,6,4
13,0,22,5,13,3,2,0,0,0,0,0,0,0,0,3,3773,0,1,6,0
14,1,3,3,0,3,2,0,0,0,0,0,0,0,0,3,3773,1,1,7,5
15,5,146,17,33,4,2,2,0,0,0,0,0,0,0,3,3773,3,2,7,2
16,2,8,8,9,1,3,2,0,0,0,0,0,0,0,3,3773,0,4,8,4
17,0,9,3,1,4,3,2,0,0,0,0,0,0,0,3,3773,0,2,8,2
18,2,41,9,19,3,3,4,0,0,0,0,0,0,0,3,3773,0,2,9,3
19,0,8,7,26,2,3,4,0,0,0,0,0,0,0,3,3773,0,10,9,6
20,1,10,5,2,4,3,4,0,0,0,0,0,0,0,3,3773,1,7,10,2
21,5,4,3,3,1,3,4,0,0,0,0,0,0,0,3,3773,3,3,10,6
22,1,18,7,19,4,0,2,0,0,0,0,0,0,0,3,3773,1,0,11,2
23,0,4,4,3,2,0,4,0,0,0,0,0,0,0,3,3773,0,5,11,5
24,6,29,11,15,4,0,4,1,0,0,1,0,0,1,3,3981,1,3,0,6
25,0,114,42,52,4,0,1,1,0,0,1,0,0,1,3,3981,0,11,0,2
26,2,30,12,17,5,0,4,1,0,0,1,0,0,1,3,3981,0,8,1,1
27,1,87,18,36,3,0,1,1,0,0,1,0,0,1,3,3981,1,3,1,0
28,0,26,10,28,5,1,3,1,0,0,1,0,0,1,3,3981,0,1,2,4
29,6,8,7,9,5,1,4,1,0,0,1,0,0,1,3,3981,1,8,2,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474,2,18,3,10,2,3,4,1,0,0,1,0,0,19,4,2916,0,2,9,6
475,0,6,4,6,5,3,4,1,0,0,1,0,0,19,4,2916,0,0,9,2
476,0,48,8,25,4,3,4,1,0,0,1,0,0,19,4,2916,0,6,10,6
477,0,24,3,5,5,3,4,1,0,0,1,0,0,19,4,2916,0,0,10,5
478,2,123,26,63,5,0,4,1,0,0,1,0,0,19,4,2916,0,4,11,2
479,0,24,7,6,4,0,0,1,0,0,1,0,0,19,4,2916,0,1,11,0
480,2,20,13,17,4,0,4,1,0,0,1,0,0,20,4,826,0,4,0,6
481,0,15,3,4,3,0,2,1,0,0,1,0,0,20,4,826,0,7,0,3
482,46,189,72,129,4,0,3,1,0,0,1,0,0,20,4,826,1,3,1,1
483,0,25,19,27,3,0,4,1,0,0,1,0,0,20,4,826,0,8,1,6
484,0,33,11,12,5,1,1,1,0,0,1,0,0,20,4,826,0,4,2,4
485,0,14,7,13,5,1,0,1,0,0,1,0,0,20,4,826,0,4,2,0
486,0,38,22,47,4,1,1,1,0,0,1,0,0,20,4,826,0,4,3,6
487,7,169,43,85,4,1,3,1,0,0,1,0,0,20,4,826,4,12,3,5
488,0,20,17,21,3,1,0,1,0,0,1,0,0,20,4,826,0,4,4,5
489,0,17,10,18,4,1,4,1,0,0,1,0,0,20,4,826,0,3,4,3
490,0,96,47,161,4,2,3,1,0,0,1,0,0,20,4,826,0,11,5,6
491,0,38,13,11,3,2,1,1,0,0,1,0,0,20,4,826,0,5,5,5
492,3,12,11,9,4,2,2,1,0,0,1,0,0,20,4,826,2,6,6,6
493,0,9,8,1,5,2,4,1,0,0,1,0,0,20,4,826,0,6,6,6
494,0,23,21,22,3,2,2,1,0,0,1,0,0,20,4,826,0,7,7,4
495,0,21,6,3,4,2,4,1,0,0,1,0,0,20,4,826,0,5,7,3
496,0,30,27,19,5,3,3,1,0,0,1,0,0,20,4,826,0,6,8,1
497,0,63,16,59,3,3,4,1,0,0,1,0,0,20,4,826,0,11,8,4
498,1,35,3,25,5,3,4,1,0,0,1,0,0,20,4,826,1,1,9,6
499,1,15,4,8,5,3,4,1,0,0,1,0,0,20,4,826,1,1,9,5
500,2,50,13,29,4,3,4,1,0,0,1,0,0,20,4,826,0,8,10,0
501,0,154,23,31,4,3,0,1,0,0,1,0,0,20,4,826,0,4,10,0
502,0,9,6,5,2,0,2,1,0,0,1,0,0,20,4,826,0,9,11,4
503,0,20,19,112,4,0,2,1,0,0,1,0,0,20,4,826,0,5,11,3